[package]
name = "margatroidd"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "margatroidd"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
app_runtime_plugin = { path = "../../crates/mecs/app_runtime_plugin" }
core_plugin = { path = "../../crates/mecs/core_plugin" }
http_server_plugin = { path = "../../crates/mecs/http_server_plugin" }
margatroid_defaults = { path = "../../crates/margatroid/defaults" }
margatroid_protocol = { path = "../../crates/margatroid/protocol" }
paths = { path = "../../crates/margatroid/paths" }
serde = { workspace = true }
signal_plugin = { path = "../../crates/mecs/signal_plugin" }
toml = "0.8"
tracing = { workspace = true }

[dev-dependencies]
tempfile = "3"
