[package]
name = "margatroidd"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "margatroidd"
path = "src/main.rs"

[dependencies]
app_runtime_plugin = { path = "../../crates/mecs/app_runtime_plugin" }
core_plugin = { path = "../../crates/mecs/core_plugin" }
margatroid_defaults = { path = "../../crates/margatroid/defaults" }
margatroid_protocol = { path = "../../crates/margatroid/protocol" }
tracing = { workspace = true }
