[package]
name = "margatroid_daemon"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "margatroid-daemon"
path = "src/main.rs"

[dependencies]
agent_image_loader_plugin = { path = "../../crates/margatroid/agent_image_loader_plugin" }
agent_plugin = { path = "../../crates/margatroid/agent_plugin" }
app_runtime_plugin = { path = "../../crates/mecs/app_runtime_plugin" }
async_runtime_plugin = { path = "../../crates/mecs/async_runtime_plugin" }
core_plugin = { path = "../../crates/mecs/core_plugin" }
connection_plugin = { path = "../../crates/margatroid/connection_plugin" }
config_plugin = { path = "../../crates/margatroid/config_plugin" }
dto_plugin = { path = "../../crates/margatroid/dto_plugin" }
inference_plugin = { path = "../../crates/margatroid/inference_plugin" }
log_plugin = { path = "../../crates/mecs/log_plugin" }
lua_runtime_plugin = { path = "../../crates/margatroid/lua_runtime_plugin" }
memory_plugin = { path = "../../crates/margatroid/memory_plugin" }
mcl_plugin = { path = "../../crates/margatroid/mcl_plugin" }
resource_id_plugin = { path = "../../crates/margatroid/resource_id_plugin" }
server_plugin = { path = "../../crates/mecs/server_plugin" }
tool_plugin = { path = "../../crates/margatroid/tool_plugin" }
tracing = { workspace = true }
workspace_plugin = { path = "../../crates/margatroid/workspace_plugin" }
