[package]
name = "daemon_lifecycle_plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
app_runtime_plugin = { path = "../../mecs/app_runtime_plugin" }
async_runtime_plugin = { path = "../../mecs/async_runtime_plugin" }
axum = { workspace = true }
core_plugin = { path = "../../mecs/core_plugin" }
http_server_plugin = { package = "server_plugin", path = "../../mecs/server_plugin" }
signal_plugin = { path = "../../mecs/signal_plugin" }
tracing = { workspace = true }
