[package]
name = "api_plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
app_runtime_plugin = { path = "../../mecs/app_runtime_plugin" }
core_plugin = { path = "../../mecs/core_plugin" }
margatroid_protocol = { path = "../protocol" }
margatroid_types = { path = "../types" }
serde_json = { workspace = true }
server_plugin = { path = "../../mecs/server_plugin" }
tracing = { workspace = true }

[dev-dependencies]
async_runtime_plugin = { path = "../../mecs/async_runtime_plugin" }
