[package]
name = "builtin_tool_plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
app_runtime_plugin = { path = "../../mecs/app_runtime_plugin" }
core_plugin = { path = "../../mecs/core_plugin" }
lua_plugin = { path = "../tool_definition_plugins/lua_plugin" }
margatroid_types = { path = "../types" }
shell_plugin = { path = "../tool_definition_plugins/shell_plugin" }
skill_plugin = { path = "../tool_definition_plugins/skill_plugin" }
tool_plugin = { path = "../tool_plugin" }
workflow_plugin = { path = "../tool_definition_plugins/workflow_plugin" }

[dev-dependencies]
tokio = { workspace = true }
agent_plugin = { path = "../agent_plugin" }
async_runtime_plugin = { path = "../../mecs/async_runtime_plugin" }
tempfile = "3"
