[package]
name = "http_server_plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
app_runtime_plugin = { path = "../app_runtime_plugin" }
axum = { workspace = true }
core_plugin = { path = "../core_plugin" }
tokio = { workspace = true }
tower-http = { version = "0.6", features = ["limit", "timeout"] }
tracing = { workspace = true }
