[package]
name = "margatroid_defaults"
version = "0.1.0"
edition = "2024"

[dependencies]
app_runtime_plugin = { path = "../../mecs/app_runtime_plugin" }
async_runtime_plugin = { path = "../../mecs/async_runtime_plugin" }
core_plugin = { path = "../../mecs/core_plugin" }
daemon_lifecycle_plugin = { path = "../daemon_lifecycle_plugin" }
external_event_plugin = { path = "../../mecs/external_event_plugin" }
http_server_plugin = { package = "server_plugin", path = "../../mecs/server_plugin" }
log_plugin = { path = "../../mecs/log_plugin" }
daemon_api_plugin = { path = "../daemon_api_plugin" }
signal_plugin = { path = "../../mecs/signal_plugin" }
