[package]
name = "tool_plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
agent_plugin = { path = "../agent_plugin" }
app_runtime_plugin = { path = "../../mecs/app_runtime_plugin" }
async_runtime_plugin = { path = "../../mecs/async_runtime_plugin" }
core_plugin = { path = "../../mecs/core_plugin" }
futures-util = { workspace = true }
margatroid_types = { path = "../types" }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tempfile = "3"
