[package]
name = "agent_plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
app_runtime_plugin = { path = "../../mecs/app_runtime_plugin" }
core_plugin = { path = "../../mecs/core_plugin" }
inference_plugin = { path = "../inference_plugin" }
margatroid_types = { path = "../types" }
mcl_plugin = { path = "../mcl_plugin" }
memory_plugin = { path = "../memory_plugin" }
serde_json = { workspace = true }
tool_plugin = { path = "../tool_plugin" }
tracing = { workspace = true }

[dev-dependencies]
async_runtime_plugin = { path = "../../mecs/async_runtime_plugin" }
serde = { workspace = true }
tempfile = "3"
